#!/bin/sh

CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)

[ "$STATUS" = "Discharging" ] && [ "$CAPACITY" -lt 15 ] && \
/usr/bin/notify-send -u critical -t 60000 -a power_supply_low "Low Battery" "You are running low on battery ($CAPACITY%).\nPlease plug in the charger."
