#!/bin/sh

THRESHOLD=10485760 # 10 * 1024 * 1024 : 10Gb
AVAILABLE=$(df -lk --output=avail / | tail -n1)
AVAILABLE_HUMAN=$(df -lh --output=avail / | tail -n1)

if [ "${AVAILABLE}" -lt "${THRESHOLD}" ]; then
    notify-send -u critical -t 60000 -a disk_available_low "Low disk space" "You are running low on disk space (remaining: $AVAILABLE_HUMAN)."
fi
