#!/bin/bash

# put a trailing slash on the source dir to indicate *contents of* that directory

SOURCE_DIR=$1
DEST_DIR=$2

if [ ! -d "${SOURCE_DIR}" ]; then
    echo "Error: source dir not specified or not a directory"
    exit 1
fi

if [ ! -d "${DEST_DIR}" ]; then
    echo "Error: dest dir not specified or not a directory"
    exit 1
fi

rsync -raP --delete "${SOURCE_DIR}" "${DEST_DIR}"
