#!/bin/bash

SOURCE_DIR=$1
DEST_DIR=$2

if [ ! -d "${SOURCE_DIR}" ]; then
    echo "Error: source dir not specified or not a directory"
    exit 1
fi

if [ ! -d "${DEST_DIR}" ]; then
    echo "Error: source dir not specified or not a directory"
    exit 1
fi

rsync -n -raP --delete ${SOURCE_DIR} ${DEST_DIR}
