#!/bin/bash

tables_dir=~/Games/VisualPinball/tables
version=10.8.0
vpinball_exec=~/Games/VisualPinball/VisualPinball-${version}/VPinballX_GL

echo "Visual Pinball Launcher"
echo ""
echo "Please select a table:"

n=0

SAVEIFS=${IFS}
IFS=$(echo -en "\n\b")

for table_filepath in $(find ${tables_dir} -type f -name '*.vpx' | sort); do
    n=$((n+1))
    table_filename=$(basename $table_filepath)
    table_filename_no_path=${table_filename%.*}
    table_displayname=${table_filename_no_path//_/ }
    echo "[${n}] ${table_displayname}"
    eval "table_filepaths${n}=\$table_filepath"
done

IFS=$SAVEIFS

if [ "$n" -eq 0 ]; then
    echo "No tables found in ${tables_dir}"
    exit 0
fi

input=${1}
if [ -z ${input} ]; then
    read -r input
fi

if [[ "$input" =~ ^-?[0-9]+$ ]]; then
  if [ "$input" -le 0 ] || [ "$input" -gt "$n" ]; then
      echo "Invalid selection - no table matches that number"
      exit 1
  fi

  eval "table_filepath=\$table_filepaths${input}"

elif [[ "$input" =~ ^[a-zA-Z]+$ ]]; then
  table_filename=$(ls ${tables_dir} | grep -E '.vpx$' | grep -i ${input} | head -n1)

  if [ -z "${table_filename}" ]; then
    echo "Invalid selection - no table matches that name"
    exit 1
  fi

  table_filepath=${tables_dir}/$table_filename
else
  echo "Error: invalid input; please enter an integer table number or name search string"
  exit 1
fi

echo "Launching table: $table_filepath"


monitor=HDMI-A-1
hyprctl monitors | grep $monitor > /dev/null
nowState=$?
if [ $nowState = 1 ]; then
    echo "Setting up external monitor"
    hyprctl keyword monitorv2[$monitor]:disabled 0
    hyprctl keyword monitorv2[$monitor]:transform 0
    echo "Wait 5s for monitor to come up..."
    sleep 5
fi

$vpinball_exec -play "${table_filepath}"
