#!/bin/bash

DEVICE='SynPS/2 Synaptics TouchPad'

ENABLED=$(xinput --list-props "${DEVICE}" | grep 'Device Enabled' | grep -o '[01]$')

if [ "${ENABLED}" = 1 ]; then
    echo "Disbabling device: ${DEVICE}"
    xinput disable "${DEVICE}"
else
    echo "Enabling device: ${DEVICE}"
    xinput enable "${DEVICE}"
fi
